In [ ]:
import os   # file path
import pandas as pd # stoer/manipulate data
import numpy as np # numerical operations
import time # time delays
import serial # serial communication

"""Device communication functions."""
def DeviceConnect(COMPort): 
    ser = serial.Serial(COMPort, 9600, timeout = 1) 
    return ser 

ser_lcr = DeviceConnect('/dev/cu.usbmodem48FE556033311')       # LCR Meter
ser_cn740 = DeviceConnect('/dev/cu.usbserial-BG00XWYD')  # Omega CN740 (RS-485)
#parity does not match with Even
#DeviceConnect_CN740 defined

print(ser_lcr)
print(ser_cn740)

Serial<id=0x10bca7ca0, open=True>(port='/dev/cu.usbmodem48FE556033311', baudrate=9600, bytesize=8, parity='N', stopbits=1, timeout=1, xonxoff=False, rtscts=False, dsrdtr=False)
Serial<id=0x10a42d990, open=True>(port='/dev/cu.usbserial-BG00XWYD', baudrate=9600, bytesize=8, parity='N', stopbits=1, timeout=1, xonxoff=False, rtscts=False, dsrdtr=False)


In [10]:
readout = []
print(readout)
readout.append(1)
print(readout)
readout.append("a")
print(readout)

[]
[1]
[1, 'a']


In [33]:
from Functions import*

ser_lcr = DeviceConnect('/dev/cu.usbmodem48FE556033311')       # LCR Meter
readout = []

ser_lcr.write('FETCh?\n'.encode())
readout.append(ser_lcr.readline())

ser_lcr.write('FETCh?\n'.encode())
readout.append(ser_lcr.readline().decode())

ser_lcr.write('FETCh?\n'.encode())
readout.append(ser_lcr.readline().decode().strip())

print(readout)

[b'100927,-0\r\n', '100927,-0\r\n', '100927,-0']


In [27]:
readout = []
readout.append('a, b')
readout.append('c')
print(readout)
print(len(readout))

print(readout[0])
print(readout[1])

['a, b', 'c']
2
a, b
c


In [49]:
from Functions import*
ser_lcr = DeviceConnect('/dev/cu.usbmodem48FE556033311')

ser_lcr.write('BIAS:VOLTage\n'.encode())
print(ser_lcr.readline().decode().strip())

exec success


In [65]:
import numpy as np 
a = float(np.log10(100))
print(a)
a,a,a

2.0


(2.0, 2.0, 2.0)

In [101]:
temp = np.logspace(1,10,10)
print(temp)
print(temp[0])

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09 1.e+10]
10.0


In [84]:
import numpy as np  
import pandas as pd

a = np.array([0,5,10,15])
df = pd.DataFrame(a)
df2 = pd.DataFrame(a, columns = ['Voltage (V)'])
df3 = pd.DataFrame(a, columns = ['Voltage (V)'], index = ['a','b','c','d'])
print(df) 
print(df2) 
print(df3) 

    0
0   0
1   5
2  10
3  15
   Voltage (V)
0            0
1            5
2           10
3           15
   Voltage (V)
a            0
b            5
c           10
d           15


In [104]:
a = np.array([1.1, 2.2 ,3.3 ,4.4 ,5.5])
b = np.round(a)
c = np.round(a).astype(int)
print(f"a = {a}")
print(f"b = {b}")
print(f"c = {c}") 

a = [1.1 2.2 3.3 4.4 5.5]
b = [1. 2. 3. 4. 6.]
c = [1 2 3 4 6]


In [96]:
temp = np.array([1,2,3,4,5])
print(f"temp = {temp}")
a = temp[0]
print(f"a = {a}")
b = (temp[0],temp[1])
print(f"b = {b}")

temp = [1 2 3 4 5]
a = 1
b = (np.int64(1), np.int64(2))


In [110]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = np.array([11,12,13,14,15])
d = np.vstack([a, b])
e = np.vstack([d, c])
print(f"d={d}")
print(f"e={e}")
print(e.shape)
print(len(e))
print(e.size)
print(e.ndim)


d=[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
e=[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
(3, 5)
3
15
2


In [153]:
temp = np.array([0,0,0,0])
for i in range(0,5):
    temp = np.vstack([temp, [i, 2*i, 3*i, 4*i]])
print(temp) 
temp.shape

temp1=temp[::,0]
temp2=temp[::,1]
temp3=temp[2,::]
print(temp1)
print(temp2)
print(temp3)
#print(np.delete(temp, 0, axis = 0))
#print(np.delete(temp, 0, axis = 1))
#print(np.delete(temp, 0, axis = None))


[[ 0  0  0  0]
 [ 0  0  0  0]
 [ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]
[0 0 1 2 3 4]
[0 0 2 4 6 8]
[1 2 3 4]


In [165]:
k = "10a"
i = "5b"
print(k)
print(i)
'-'.join([k,i])

10a
5b


'10a-5b'

In [169]:
a = "1,2"
print(a)
b=a.split(',')
print(b)

1,2
['1', '2']


In [182]:
a1 = np.array([0])
b1 = np.array([0])

for i in range(0,10):
    a1 = np.vstack([a1, i])
    b1 = np.append(b1, i)
print(a1)
print(b1)

[[0]
 [0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[0 0 1 2 3 4 5 6 7 8 9]


In [190]:
frequencies = np.logspace(1, 6, 4) 
print(frequencies)
df = pd.DataFrame(frequencies, columns = ['Frequency'])
print(df)

[1.00000000e+01 4.64158883e+02 2.15443469e+04 1.00000000e+06]
        Frequency
0       10.000000
1      464.158883
2    21544.346900
3  1000000.000000


In [216]:
freq = np.array([100,200,300,400])
df = pd.DataFrame(freq, columns = ['freq'])

a1 = []
a2 = []
a3 = []

for i in range(0,4):
    a1 = np.append(a1, i)
    a2 = np.append(a2, i*2)
    a3 = np.append(a3, i*3)

df['a1'] = a1
df['a2'] = a2      
df['a3'] = a3

c = 'a,b,c,d'
c = c.split(',')
df['alphabet'] = c

print(df) 

   freq   a1   a2   a3 alphabet
0   100  0.0  0.0  0.0        a
1   200  1.0  2.0  3.0        b
2   300  2.0  4.0  6.0        c
3   400  3.0  6.0  9.0        d
